# Cloudflare Worker with Next.js
name = "iborrow-system"
main = "worker.js"
compatibility_date = "2025-11-27"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

# D1 Database Binding
[[d1_databases]]
binding = "DB"
database_name = "iborrow"
database_id = "51ddaea3-c7f4-4c5c-ad87-0a4e592e0154"
